name: KNLP

# on 表示触发CI的动作，可以为push、pull request
on: [push]

permissions:
  contents: read

# 一次CI需要做哪些事情，jobs表示可以有多个任务
jobs:
  job:
    runs-on: ubuntu-latest
    # github 可用的运行环境
    #    windows-2019
    #    ubuntu-20.04
    #    macos-10.15

    # 每个job 由多个step组成
    steps:
    # https://github.com/actions/checkout 使用指定的版本来检测
    - uses: actions/checkout@v3
    # name表示一个步骤的名称
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      # 通过run来运行命令 在ubuntu-latest上执行命令
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        flake8 . --count
      # --count 打印错误总数
    - name: run test_all
        run: |
          test/test_all.py